In [1]:
import cv2
#importing the OpenCV Function

Reading the Image

The imread function converts the image in to N-Dimensional array,
 if it is color image it converts them in to (0-255 values) in (b,g,r) format and results in 3_Dimensioonal Array
 and if it is black_n_white image it converts them in to (0-255 values) in (0, 1)(black or white) format and results in 2_Dimensioonal Array

In [2]:
color_image = cv2.imread("image.jpg", 1)
#when Attribute is 1 it shows the color Image
black_n_white_image = cv2.imread("image.jpg", 0)
#when Attribute is 1 it shows the color Image

Showing the n_dimensional array

In [5]:
print(type(color_image))
print(type(black_n_white_image))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Printing the shape of image

In [8]:
print(color_image.shape)
#printing the shape of color image (3_Dimensional array)
print(black_n_white_image.shape)
#printint the shape of black and White image (2_Dimensional array)

(275, 183, 3)
(275, 183)


Printing the arrays

In [10]:
print(color_image)
#the array of color Image (3_Dimensional)

[[[178 161  58]
  [178 161  58]
  [178 161  58]
  ...
  [183 165  58]
  [183 165  58]
  [183 164  59]]

 [[179 162  59]
  [179 162  59]
  [179 162  59]
  ...
  [183 165  58]
  [184 165  60]
  [184 165  60]]

 [[179 162  59]
  [179 162  59]
  [179 162  59]
  ...
  [182 166  60]
  [182 166  60]
  [183 166  63]]

 ...

 [[  7   9   9]
  [  7   9   9]
  [  7   9   9]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  7   9   9]
  [  7   9   9]
  [  7   9   9]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  7   9   9]
  [  7   9   9]
  [  7   9   9]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [11]:
print(black_n_white_image)
#the array of Black and White Image (2-dimensional)

[[132 132 132 ... 135 135 135]
 [133 133 133 ... 135 136 136]
 [133 133 133 ... 136 136 137]
 ...
 [  9   9   9 ...   0   0   0]
 [  9   9   9 ...   0   0   0]
 [  9   9   9 ...   0   0   0]]


Showing the Color Image

In [3]:
cv2.imshow("color Image", color_image)
# the first attribute will show on the poped-up new tab as the title and second is the image

cv2.waitKey(0)
#if the wait key Attribute is 0, on pressing any key on keyboard the screen closes.

cv2.destroyAllWindows()
#distroys all the open up window

Showing the Black and White Image

In [4]:
cv2.imshow("Black and White", black_n_white_image)
cv2.waitKey(2000)
#this opens up the image window for 2000 milli-seconds
cv2.destroyAllWindows()

Resizing the Image

In [12]:
resized_image = cv2.resize(color_image, (200, 300))
#resizing the color image in to (200 * 300)
cv2.imshow("Resized Image", resized_image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

Resizing the image to half its original size or double of its size

In [20]:
double_resize_image = cv2.resize(black_n_white_image, (int(black_n_white_image.shape[1]*2), int(black_n_white_image.shape[0]*2)))
cv2.imshow("Double the size", double_resize_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
# making the Size of of the image to the double of its original Value

In [21]:
half_resize_image = cv2.resize(black_n_white_image, (int(black_n_white_image.shape[1]/2), int(black_n_white_image.shape[0]/2)))
cv2.imshow("Half the size", half_resize_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
# making the Size of of the image to the Half of its original Value

Recognising the Face


=> Create a Casscade Classifier which has the Image properties 
=> Read the Image using imread converting them to n-dimensional array
=> Search for the rows and columns of the face numpy n-dim array(for face rectange coordinates)
=> Display the image with rectangular Face


In [23]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
#defining the Haarcascade classifier which contains all the attributes of faces 

In [27]:
image = color_image

In [28]:
faces = face_cascade.detectMultiScale(image, scaleFactor = 1.03, minNeighbors = 3)
#making a face Cascade object to detect the the coordinates of rectangle with precision of 1.03 and minimum neighbors as 3
#decreases the face by 5% every time of the image and smaller the image more the accuracy

In [29]:
print(faces)
#We got the coordinates of the rectangle of the Face inscribing it

[[41 78 95 95]]


Plotting the rectangle coordinates around the Face

In [30]:
#We have the coordinates as the initial (x,y) coordinates and the diagonally opposite coordinates (x+w, y+h)
for x, y, w, h in faces:
    image = cv2.rectangle(image, (x,y), (x + w, y + h), (0, 255, 0), 1)
cv2.imshow("Recognized_image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

Testing this for different set of images

In [33]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
image = cv2.imread("g_image.jpg", 1)
faces = face_cascade.detectMultiScale(image, scaleFactor = 1.03, minNeighbors = 4)
print(faces)
for x, y, w, h in faces:
    image = cv2.rectangle(image, (x,y), (x + w, y + h), (0, 255, 0), 1)
cv2.imshow("Recognized_image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[239 220  50  50]
 [377 214  38  38]
 [108 224  40  40]
 [ 65  95  46  46]
 [329 105  46  46]
 [410  57  33  33]
 [  5  41  39  39]
 [212  26  33  33]
 [189 148  41  41]]


In [36]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
image = cv2.imread("group_image.png", 1)
faces = face_cascade.detectMultiScale(image, scaleFactor = 1.02, minNeighbors = 4)
print(faces)
for x, y, w, h in faces:
    image = cv2.rectangle(image, (x,y), (x + w, y + h), (0, 255, 0), 1)
cv2.imshow("Recognized_image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 58 282  32  32]
 [138 282  28  28]
 [202 286  32  32]
 [275 285  31  31]
 [ 68 209  29  29]
 [130 212  34  34]
 [272 213  32  32]
 [214 212  27  27]
 [118 245  52  52]
 [203  71  29  29]
 [ 67 141  29  29]
 [203 142  31  31]
 [267  72  31  31]
 [271 141  32  32]
 [137 144  32  32]
 [ 65  70  33  33]
 [132  72  31  31]]


()
